#ifndef __SOUND_STRINGS__
#define __SOUND_STRINGS__

#include <string>

#define SOUND_GAME_ENTER_WARP "/GAME/SOUNDS/WARP.WAV"

// Treasure pickup sounds
#define SOUND_GAME_TREASURE_COIN        "/GAME/SOUNDS/COIN.WAV"         // 100 pts
#define SOUND_GAME_TREASURE_GOLDBAR     "/GAME/SOUNDS/TREASURE.WAV"     // 500 pts
#define SOUND_GAME_TREASURE_RING        "/GAME/SOUNDS/RINGS.WAV"        // 1500 pts
#define SOUND_GAME_TREASURE_CHALICE     "/GAME/SOUNDS/PICKUP1.WAV"      // 2500 pts
#define SOUND_GAME_TREASURE_CROSS       "/GAME/SOUNDS/CROSS.WAV"        // 5000 pts
#define SOUND_GAME_TREASURE_SCEPTER     "/GAME/SOUNDS/SCEPTER.WAV"      // 7500 pts
#define SOUND_GAME_TREASURE_GECKO       "/GAME/SOUNDS/PICKUP2.WAV"      // 10000 pts
#define SOUND_GAME_TREASURE_CROWN       "/GAME/SOUNDS/PICKUP1.WAV"      // 15000 pts
#define SOUND_GAME_TREASURE_SKULL       "/GAME/SOUNDS/PICKUP1.WAV"      // 25000 pts

// Ammo pickup sounds
#define SOUND_GAME_PICKUP_AMMUNITION    "/GAME/SOUNDS/AMMUNITION.WAV"
#define SOUND_GAME_PICKUP_MAGIC         "/GAME/SOUNDS/MAGICPOWERUP.WAV"

// Health pickups
#define SOUND_GAME_PICKUP_FOODITEM      "/GAME/SOUNDS/FOODITEM.WAV"
#define SOUND_GAME_PICKUP_MILK          "/GAME/SOUNDS/MILK.WAV"
#define SOUND_GAME_PICKUP_POTION        "/GAME/SOUNDS/MILK.WAV"

// Powerup pickups
#define SOUND_GAME_PICKUP_CATNIP       "/GAME/SOUNDS/CATNMAG.WAV"

// Checkpoint flags
#define SOUND_GAME_FLAG_RISE       "/GAME/SOUNDS/FLAGRISE.WAV"
#define SOUND_GAME_FLAG_WAVE       "/GAME/SOUNDS/FLAGWAVE.WAV"

#endif