#ifndef __SOUND_STRINGS__
#define __SOUND_STRINGS__

#include <string>

#define SOUND_GAME_ENTER_WARP "/GAME/SOUNDS/WARP.WAV"

// Treasure pickup sounds
#define SOUND_GAME_TREASURE_COIN        "/GAME/SOUNDS/COIN.WAV"         // 100 pts
#define SOUND_GAME_TREASURE_GOLDBAR     "/GAME/SOUNDS/TREASURE.WAV"     // 500 pts
#define SOUND_GAME_TREASURE_RING        "/GAME/SOUNDS/RINGS.WAV"        // 1500 pts
#define SOUND_GAME_TREASURE_CHALICE     "/GAME/SOUNDS/PICKUP1.WAV"      // 2500 pts
#define SOUND_GAME_TREASURE_CROSS       "/GAME/SOUNDS/CROSS.WAV"        // 5000 pts
#define SOUND_GAME_TREASURE_SCEPTER     "/GAME/SOUNDS/SCEPTER.WAV"      // 7500 pts
#define SOUND_GAME_TREASURE_GECKO       "/GAME/SOUNDS/PICKUP2.WAV"      // 10000 pts
#define SOUND_GAME_TREASURE_CROWN       "/GAME/SOUNDS/PICKUP1.WAV"      // 15000 pts
#define SOUND_GAME_TREASURE_SKULL       "/GAME/SOUNDS/PICKUP1.WAV"      // 25000 pts

// Ammo pickup sounds
#define SOUND_GAME_PICKUP_AMMUNITION    "/GAME/SOUNDS/AMMUNITION.WAV"
#define SOUND_GAME_PICKUP_MAGIC         "/GAME/SOUNDS/MAGICPOWERUP.WAV"

// Health pickups
#define SOUND_GAME_PICKUP_FOODITEM      "/GAME/SOUNDS/FOODITEM.WAV"
#define SOUND_GAME_PICKUP_MILK          "/GAME/SOUNDS/MILK.WAV"
#define SOUND_GAME_PICKUP_POTION        "/GAME/SOUNDS/MILK.WAV"

// Powerup pickups
#define SOUND_GAME_PICKUP_CATNIP       "/GAME/SOUNDS/CATNMAG.WAV"

// Checkpoint flags
#define SOUND_GAME_FLAG_RISE       "/GAME/SOUNDS/FLAGRISE.WAV"
#define SOUND_GAME_FLAG_WAVE       "/GAME/SOUNDS/FLAGWAVE.WAV"

// Crate death sounds
#define SOUND_GAME_CRATE_BREAK1    "/GAME/SOUNDS/CRATEBREAK.WAV"
#define SOUND_GAME_CRATE_BREAK2    "/GAME/SOUNDS/CRATEBREAK2.WAV"

// Powder keg explosion
#define SOUND_LEVEL1_KEG_EXPLODE   "/LEVEL1/SOUNDS/KEGBOOM.WAV"

// LEVEL 1 enemy sounds

// LEVEL1 - Soldier
#define SOUND_LEVEL1_SOLDIER_DEATH         "/LEVEL1/SOUNDS/SOLDIER/00320006.WAV"
#define SOUND_LEVEL1_SOLDIER_DAMAGED       "/LEVEL1/SOUNDS/SOLDIER/00320005.WAV"
#define SOUND_LEVEL1_SOLDIER_THROWN        "/LEVEL1/SOUNDS/SOLDIER/00340016.WAV"
#define SOUND_LEVEL1_SOLDIER_ENTER_AGGRO   "/LEVEL1/SOUNDS/SOLDIER/00320020.WAV"
#define SOUND_LEVEL1_SOLDIER_MELEE_ATTACK  "/LEVEL1/SOUNDS/SOLDIER/RFHEADBT8-22.WAV"
#define SOUND_LEVEL1_SOLDIER_SHOOT         "/LEVEL1/SOUNDS/SOLDIER/SOLGUNFR8-22.WAV"

// LEVEL1 - Officer
#define SOUND_LEVEL1_OFFICER_DEATH1        "/LEVEL1/SOUNDS/OFFICER/00340014.WAV"
#define SOUND_LEVEL1_OFFICER_DEATH2        "/LEVEL1/SOUNDS/OFFICER/00340015.WAV"
#define SOUND_LEVEL1_OFFICER_THROWN1       "/LEVEL1/SOUNDS/OFFICER/00340017.WAV"
#define SOUND_LEVEL1_OFFICER_THROWN2       "/LEVEL1/SOUNDS/OFFICER/00340018.WAV"
#define SOUND_LEVEL1_OFFICER_ENTER_AGRO    "/LEVEL1/SOUNDS/OFFICER/00340024.WAV"
#define SOUND_LEVEL1_OFFICER_HA_TOUCHE     "/LEVEL1/SOUNDS/OFFICER/00340027.WAV"
#define SOUND_LEVEL1_OFFICER_EHM1          "/LEVEL1/SOUNDS/OFFICER/EHEM1.WAV"
#define SOUND_LEVEL1_OFFICER_EHM2          "/LEVEL1/SOUNDS/OFFICER/EHEM2.WAV"
#define SOUND_LEVEL1_OFFICER_MELEE_ATTACK  "/LEVEL1/SOUNDS/OFFICER/OFCSWSTB8-22.WAV"

// LEVEL1 - Rat
#define SOUND_LEVEL1_RAT_DEATH             "/GAME/SOUNDS/MOUSEKILL.WAV"
#define SOUND_LEVEL1_RAT_THROW_BOMB        "/GAME/SOUNDS/THRWBOMB.WAV"

#endif